# Generated by Django 4.0 on 2021-12-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='point',
            field=models.IntegerField(default=0),
        ),
    ]
